---
version: "3.9"
name: hypercarry-dev
services:
  postgres-local:
    container_name: postgres-local
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: hypercarry
    volumes:
      - postgres-local:/var/lib/postgresql/data

  pgadmin-local:
    container_name: pgadmin-local
    image: dpage/pgadmin4
    restart: always
    ports:
      - "15432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-local:/var/lib/pgadmin

  minio:
    container_name: minio-local
    image: quay.io/minio/minio:RELEASE.2022-02-18T01-50-10Z
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: "minio_user"
      MINIO_ROOT_PASSWORD: "minio_password"
      MINIO_ADDRESS: ":9000"
      MINIO_CONSOLE_ADDRESS: ":9001"
    volumes:
      - minio-local:/var/lib/minio
    command: minio server /var/lib/minio

volumes:
  postgres-local:
  pgadmin-local:
  minio-local:
    driver: local
