import "./globals.css";

import type { Metadata } from "next";
import { headers } from "next/headers";

import Provider from "./provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = (await headers()).get("cookie");
  return (
    <html lang="en">
      <body>
        <Provider cookies={cookie}>{children}</Provider>
      </body>
    </html>
  );
}
