[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]

[dependencies]
"@openzeppelin-contracts" = "5.1.0"
forge-std = "1.9.4"

[soldeer]
remappings_version = false

[rpc_endpoints]
anvil = "http://localhost:8545"
opbnb-mainnet = "https://opbnb-mainnet-rpc.bnbchain.org/"
opbnb-testnet = "https://opbnb-testnet-rpc.bnbchain.org/"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
